### PR TITLE
Fix to work on EBCDIC; default to CP1252

### PR DESCRIPTION
**Pull request by khwilliamson**

### CODE REVIEW

**Comment by khwilliamson** [comment]
Commit 9eb5dc8 should be merged with b38f29b as it is a correction to that one.
b7746e3 should be merged with b012e8c 

I noticed that one file had two VERSION= statements.  

I made smallish commits, as that is what p5p wants.  You may wish to squash some.

**Comment by theory** [comment]
I'm fine to have them all. Would you mind reverting all the VERSION settings to `3.29_1`?

**Comment by khwilliamson** [comment]
Could you just skip the commits that upped the version numbers?  I thought I was helping you out.

**Comment by khwilliamson** [comment]
I thought I was helping you out by doing them.  But they are in commits that only bump the version numbers, so you could, I presume, just don't accept those 2 commits.

**Comment by theory** [comment]
More likely I will just change it after merging all these changes. To much of a PITA to cherry-pick from 22 commits.

**Comment by khwilliamson** [comment]
It's easy for me to revert those two commits locally, and then rebase so that it looks like a 23rd commit that goes back to _1.  Or you could refuse all the commits, and I delete my fork, and then refork, and resubmit the commits so all are correct.  There may be something easier, that I don't know.  In blead, once you have pushed something, you can't retract it.  I don't know if that's the case here.

**Comment by rjbs** [comment]
FWIW, I think my general workflow here matches the usual GitHub thing:

All pull requests are based on named branches.  It is key that they are not based on master (or the default branch, if something else).  Then the PR associates with the branch name.

If someone requests rework, I just force push my amended branch up, and now the PR is for that set of changes.  In this case, Karl could `git rebase -i` to drop the 1-2 commits, force push, and the PR would now be for the new branch.

In my experience, this doesn't work properly on a PR from master, but it shouldn't be hard to try find out out. :)

**Comment by khwilliamson** [comment]
Before I try this, I did not do a checkout on my local machine.  Off the top of your head, is that a problem, or not.

**Comment by theory** [comment]
Yeah. I recommend that you:

    git checkout -b ebcdic
    git push origin -u ebcdic
    git checkout master
    git remote add upstream https://github.com/theory/pod-simple.git
    git fetch upstream
    git reset --hard upstream/master

That will move your work to a branch named "ebcdic" and reset  your master to be the same as upstream master. Then close this PR, open a new one from the "ebcdic" branch, and continue working from there.

**Comment by khwilliamson** [comment]
On 02/05/2015 04:14 PM, David E. Wheeler wrote:
> Yeah. I recommend that you:
>
> |git checkout -b ebcdic
> git push origin -u ebcdic
> git checkout master
> git remote add upstream https://github.com/theory/pod-simple.git
> git fetch upstream
> git reset --hard upstream/master
> |

Will do

>
> That will move your work to a branch named "ebcdic" and reset your
> master to be the same as upstream master. Then close this PR, open a new
> one from the "ebcdic" branch, and continue working from there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/63#issuecomment-73150713>.
>

I don't see how to close a pull request

**Comment by theory** [comment]
I can do it.

**Comment by khwilliamson** [comment]
On 02/05/2015 04:14 PM, David E. Wheeler wrote:
> Yeah. I recommend that you:
>
> |git checkout -b ebcdic
> git push origin -u ebcdic
> git checkout master
> git remote add upstream https://github.com/theory/pod-simple.git
> git fetch upstream
> git reset --hard upstream/master
> |
>
> That will move your work to a branch named "ebcdic" and reset your
> master to be the same as upstream master. Then close this PR, open a new
> one from the "ebcdic" branch, and continue working from there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/63#issuecomment-73150713>.
>

I did as you said, and get this

! [rejected]        ebcdic -> ebcdic (non-fast-forward)
error: failed to push some refs to 
'https://github.com/khwilliamson/pod-simple.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by theory** [comment]
Which command did that?

**Comment by khwilliamson** [comment]
On 02/05/2015 05:21 PM, David E. Wheeler wrote:
> Which command did that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/63#issuecomment-73158706>.
>

Sorry,

git push

from my local machine, to upload the rebased, tested patches

**Comment by theory** [comment]
Oh, after all that stuff? If you have rebased, you'll need to use `git push origin --force`

**Comment by khwilliamson** [comment]
On 02/05/2015 05:27 PM, David E. Wheeler wrote:
> |git push origin --force|

That worked, travis is checking now

**Pull request closed without merging**
