### PR TITLE
I screwed up and used '$] >='; that can have floating pt round-off.  use 'ge' instead

### PR DESCRIPTION
**Pull request by khwilliamson**
Sorry

### CODE REVIEW

**Comment by khwilliamson** [comment]
Well here is my latest version.  It doesn't apply cleanly to yours because of divergence.  I'm not sure how best to tweak the two tests; you may want to make changes.  That long regex which lists as many ascii characters as possible is gone.  This is because I was told that the tool chain requires a minimum version of 5.6, and :ascii: etc. are in that release.

**Comment by theory** [comment]
Well, I wonder if I should do a final release with the currently-committed changes, with a note that it will be the last to support Perls < 5.6.

All the tests pass on Travis and GitHub says it can be merged cleanly. What divergence are you seeing?

**Comment by khwilliamson** [comment]
On 01/07/2015 10:26 PM, David E. Wheeler wrote:
> Well, I wonder if I should do a final release with the
> currently-committed changes, with a note that it will be the last to
> support Perls < 5.6.
>
> All the tests pass on Travis and GitHub says it can be merged cleanly.
> What divergence are you seeing?

Before I fixed the missing {, it was failing Travis, which only goes 
back to 5.8.  But I'll revise it to work on before 5.6.  It's actually 
easier now that I realize that invariants are what are needed, not just 
ASCII.

**Comment by theory** [comment]
I cherry-picked ac4c619 in 3f62a263. Pays to install Perl 5.6 and try it, eh?

**Pull request closed without merging**
