### PR TITLE
Ebcdic

### PR DESCRIPTION
**Pull request by khwilliamson**

### CODE REVIEW

**Comment by theory** [comment]
From 5.6.2:

> t/encod04.t ....... 1/5 Undefined subroutine &utf8::unicode_to_native called at t/encod04.t line 25.
> t/encod04.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
> Failed 4/5 subtests

**Comment by khwilliamson** [comment]
On 02/06/2015 10:20 AM, David E. Wheeler wrote:
>  From 5.6.2:
>
>     t/encod04.t ....... 1/5 Undefined subroutine
>     &utf8::unicode_to_native called at t/encod04.t line 25.
>     t/encod04.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
>     Failed 4/5 subtests
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/64#issuecomment-73276123>.
>

Thanks for catching that.  I'll fix that and make the ascii_order.pl not 
crash on early EBCDICs.

Do you want these as new commits, or do you want to close the current PR 
and I'll combine these into the appropriate existing commits?

I wonder if it's worth adding a warning in the Pod::Simple import for 
early EBCDICS that it doesn't work all that well, but proceeding anyway. 
  (There actually may be none of these in existence.)

**Comment by theory** [comment]
No, go ahead and just make those commits to your ebcdic branch and push them. That will automatically update this PR.

No opinions on EBCDIC warnings.

**Comment by khwilliamson** [comment]
On 02/06/2015 11:40 AM, David E. Wheeler wrote:
> No, go ahead and just make those commits to your ebcdic branch and push
> them. That will automatically update this PR.
>
> No opinions on EBCDIC warnings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/64#issuecomment-73289457>.
>
Now done

**Comment by theory** [comment]
Would you mind rebasing this on my master, @khwilliamson?

**Comment by khwilliamson** [comment]
On 02/06/2015 05:13 PM, David E. Wheeler wrote:
> Would you mind rebasing this on my master, @khwilliamson
> <https://github.com/khwilliamson>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/64#issuecomment-73337442>.
>

On my local system, I did a

git pull --rebase=preserve

It said

Successfully rebased and updated refs/heads/ebcdic.

I then did a git push; it said

Everything up-to-date

like nothing changed.  I don't know.  Am leaving for about 4 hours noew

**Comment by theory** [comment]
I think your master is out-of-date with mine. Mine is at f13d010, while yours still has a bunch of other stuff in it. Try this:

    git checkout master
    git remote add upstream https://github.com/theory/pod-simple.git
    git fetch theory
    git rebase --hard theory/master
    git push --force

That should get your master back to be the same as mine, then you can rebase the ebcdic branch.

**Comment by khwilliamson** [comment]
On 02/06/2015 05:44 PM, David E. Wheeler wrote:
> I think your master is out-of-date with mine. Mine is at f13d010
> <https://github.com/theory/pod-simple/commit/f13d010b8cafdca184f15b2ffd25ec351eff74ef>,
> while yours still has a bunch of other stuff in it. Try this:
>

Didn't work


> |git checkout master
Switched to branch 'master'
Your branch and 'origin/master' have diverged,
and have 2 and 22 different commits each, respectively.
   (use "git pull" to merge the remote branch into yours)

> git remote add upstream https://github.com/theory/pod-simple.git
fatal: remote upstream already exists

> git fetch theory
fatal: 'theory' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


> git rebase --hard theory/master

--hard is not a legal option to rebase


$ git remote show
origin
upstream


Didn't try to do the following

**Comment by theory** [comment]
Sorry, I corrected my typos, but I guess you saw only the email. Here it is again:

    git checkout master
    git remote add upstream https://github.com/theory/pod-simple.git
    git fetch upstream
    git reset --hard upstream/master
    git push --force

**Comment by khwilliamson** [comment]
On 02/07/2015 10:47 AM, David E. Wheeler wrote:
> Sorry, I corrected my typos, but I guess you saw only the email. Here it
> is again:
>
> |git checkout master
> git remote add upstream https://github.com/theory/pod-simple.git
> git fetch upstream
> git reset --hard upstream/master
> git push --force
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/64#issuecomment-73374462>.
>

That updated my github to be the same as yours.  Now I think I should 
switch to branch ebcdic and push again?

**Comment by khwilliamson** [comment]
Hmm, I just looked at this page again, and suddenly out branches aren't in sync, with my having done nothing more.  And I see that the commits on my branch are duplicated.  I don't know what to do now.

**Comment by khwilliamson** [comment]
rjbs, graciously helped me on irc, so that I think it is ok now.

**Comment by theory** [comment]
Thank you, @rjbs! Much appreciated.

Still seeing a failure on 5.6.2, though:

    t/encod04.t ....... 1/5 # Failed test 2 in t/encod04.t at line 52
    #  t/encod04.t line 52 is:       ok 0;
    # Failed test 4 in t/encod04.t at line 118 *TODO*
    #  t/encod04.t line 118 is:             ok 0;
    # Failed test 5 in t/encod04.t at line 151
    #  t/encod04.t line 151 is:             ok 0;
    t/encod04.t ....... Failed 2/5 subtests

**Comment by khwilliamson** [comment]
It turns out that test 5 will fail on v5.6 because it doesn't have the function used to resolve the ambiguity this test deliberately poses.  The solution is to make that test a todo on this early a Perl.  I did that, and tested on 5.6.2, and when I pushed here, it said 
$ git push
fatal: The current branch new-ebcdic has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin new-ebcdic

which I did, but github doesn't seem to have found it.

**Comment by khwilliamson** [comment]
Once again rjbs to the resuce

**Comment by theory** [comment]
Almost there!

    > prove -lv t/encod04.t
    t/encod04.t .. 
    1..5 todo 4 5;
    # Running under perl version 5.006002 for darwin
    # Current time local: Mon Feb  9 15:53:25 2015
    # Current time GMT:   Mon Feb  9 23:53:25 2015
    # Using Test.pm version 1.26
    ok 1
    not ok 2
    # failed to find expected control character in output
    # Failed test 2 in t/encod04.t at line 61
    #  t/encod04.t line 61 is:       ok 0;
    ok 3
    not ok 4
    # parser guessed wrong encoding expected 'CP1252' got 'UTF-8'
    # Failed test 4 in t/encod04.t at line 127 *TODO*
    #  t/encod04.t line 127 is:             ok 0;
    not ok 5
    # parser guessed wrong encoding expected 'CP1252' got 'UTF-8'
    # Failed test 5 in t/encod04.t at line 160 *TODO*
    #  t/encod04.t line 160 is:             ok 0;
    Failed 1/5 subtests 

    Test Summary Report
    -------------------
    t/encod04.t (Wstat: 0 Tests: 5 Failed: 1)
      Failed test:  2
    Files=1, Tests=5,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.02 cusr  0.00 csys =  0.04 CPU)
    Result: FAIL

**Comment by khwilliamson** [comment]
I should have seen that before.  Investigating now.

**Comment by khwilliamson** [comment]
Nothing is getting translated on 5.6.2.  That is the character \x97 is just being output as \x97 instead of being transcoded into what cp1252 thinks it should be.

My guess is this is an Encode problem.   What it says in package Pod::Simple::TranscodeSmart is this:

## Anything before 5.8.0 is GIMPY!
## This module is to be use()'d only by Pod::Simple::Transcode

I haven't touched any of this code.  The TranscodeDumb doesn't support cp1252.  

I don't know what to do about this.  We are correctly guessing 1252, but there is no transcoding going on.

**Comment by theory** [comment]
Should we add 1252 to TranscodeDumb?

**Comment by khwilliamson** [comment]
We could.  If we did, it looks like it is no longer a null-only thing, and so make_transcoder() would have to return a sub that does something for that encoding.  I don't know how to do that without investigating.

**Comment by khwilliamson** [comment]
BTW, the visible changes deadline for 5.22 is Feb 20

**Comment by theory** [comment]
So, not an Encode issue, since 5.6 does not include Encode.

I can't see what might have been returned for latin-1 on 5.6 so that it would transcode. Even if we add cp1252, TranscodeDumb still returns a no-op code ref…

**Comment by theory** [comment]
Oh, the code in master [matches `m{Dash (\x97|&#x97;|&#151;)}`](https://github.com/theory/pod-simple/blob/master/t/encod04.t#L45). Any reason not to just put that back?

**Comment by theory** [comment]
I propose to commit this change:

    diff --git a/lib/Pod/Simple/TranscodeDumb.pm b/lib/Pod/Simple/TranscodeDumb.pm
    index b3f2e06..0eb0b4c 100644
    --- a/lib/Pod/Simple/TranscodeDumb.pm
    +++ b/lib/Pod/Simple/TranscodeDumb.pm
    @@ -17,6 +17,8 @@ $VERSION = '3.29_3';
       'null'        => 1,
       'latin1'      => 1,
       'latin-1'     => 1,
    +  'cp-1252'     => 1,
    +  'cp1252'      => 1,
       %Supported,
     );
 
    diff --git a/t/encod04.t b/t/encod04.t
    index 421b5b1..8f937cb 100644
    --- a/t/encod04.t
    +++ b/t/encod04.t
    @@ -58,8 +58,12 @@ if( $guess ) {
         if( grep m{Dash &#8212}, @output_lines ) {
           ok 1;
         } else {
    -      ok 0;
    -      print "# failed to find expected control character in output\n"
    +      if( $] lt 5.007_003 && grep m{Dash (\x97|&#x97;|&#151;)}, @output_lines ) {
    +        ok 1;
    +      } else {
    +        ok 0;
    +        print "# failed to find expected control character in output\n"
    +      }
         }
       } else {
         ok 0;

**Comment by khwilliamson** [comment]
On 02/10/2015 10:34 AM, David E. Wheeler wrote:
> Oh, the code in master matches |m{Dash (\x97|&#x97;|&#151;)}|
> <https://github.com/theory/pod-simple/blob/master/t/encod04.t#L45>. Any
> reason not to just put that back?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/64#issuecomment-73744232>.
>

There is a reason not to just put it back.  It would be wrong.  The 
whole point of CP1252 is that \x97 is Unicode &#8212; correspondingly 
for other code points in the 0x80 - 0x9F range.

I don't understand how encodings worked without Encode.  Was it the case 
that the Transcode modules were supposed to do what Encode does in later 
versions?

One solution is to guess 8859 in early Perl versions, not CP1252.  I 
don't know if that behavior inconsistency would be acceptable or not.

Another solution is to make the code ref returned by TranscodeDumb not a 
no-op for CP1252, and to translate the 30ish code points that differ to 
their proper Unicode values.

**Comment by khwilliamson** [comment]
On 02/10/2015 10:44 AM, David E. Wheeler wrote:
> I propose to commit this change:
>
> |diff --git a/lib/Pod/Simple/TranscodeDumb.pm b/lib/Pod/Simple/TranscodeDumb.pm
> index b3f2e06..0eb0b4c 100644
> --- a/lib/Pod/Simple/TranscodeDumb.pm
> +++ b/lib/Pod/Simple/TranscodeDumb.pm
> @@ -17,6 +17,8 @@ $VERSION = '3.29_3';
>     'null'        => 1,
>     'latin1'      => 1,
>     'latin-1'     => 1,
> +  'cp-1252'     => 1,
> +  'cp1252'      => 1,
>     %Supported,
>   );
>
> diff --git a/t/encod04.t b/t/encod04.t
> index 421b5b1..8f937cb 100644
> --- a/t/encod04.t
> +++ b/t/encod04.t
> @@ -58,8 +58,12 @@ if( $guess ) {
>       if( grep m{Dash &#8212}, @output_lines ) {
>         ok 1;
>       } else {
> -      ok 0;
> -      print "# failed to find expected control character in output\n"
> +      if( $] lt 5.007_003 && grep m{Dash (\x97|&#x97;|&#151;)}, @output_lines ) {
> +        ok 1;
> +      } else {
> +        ok 0;
> +        print "# failed to find expected control character in output\n"
> +      }
>       }
>     } else {
>       ok 0;
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/64#issuecomment-73746138>.
>

I think this is tantamount to saying it doesn't work right in 5.6.2.  If 
so, why not just skip the test entirely?  I think, though I could be 
wrong, that people are relying on this module to take an encoding and 
translate it to standard Unicode values.  In this case we would not be 
doing that.

**Comment by theory** [comment]
> There is a reason not to just put it back.  It would be wrong.  The
> whole point of CP1252 is that \x97 is Unicode &#8212; correspondingly
> for other code points in the 0x80 - 0x9F range.

Ah, right. Well, maybe we should put in some other character that’s UTF-8 but not CP1252?

I think at one point the TranscodeDumb module was supposed to do some very basic encoding, but it was [commented out in 2003](https://github.com/theory/pod-simple/commit/d8e219f1). The changes then say:

> In an attempt to stop Perl 5.6 versions from going completely
> crazy, I've tried to basically turn off all Unicode/utf8 support
> under 5.6. Under 5.8 and above, Unicode should work fine, and
> under 5.6, all Unicode characters should be replaced with a little
> "can't render" symbol, either a "¤" or a "?".
> Many many thanks to Jarkko Hietaniemi for helping out.

The code that makes the "can't render" characters is [here in that commit](https://github.com/theory/pod-simple/commit/d8e219f1#diff-e2152ef97df0545fdc1b968383fdbbe5R1298), and [still here in the code](https://github.com/theory/pod-simple/commit/d8e219f1#diff-e2152ef97df0545fdc1b968383fdbbe5R1298). I think that's how it should work.

> Another solution is to make the code ref returned by TranscodeDumb not a
> no-op for CP1252, and to translate the 30ish code points that differ to
> their proper Unicode values.

Is it only those points in CP1252 that aren't the same as in UTF-8? If so, then yeah, that would be a decent compromise, I think, at least for this test.

**Comment by theory** [comment]
I assume you mean [these](https://github.com/theory/encode-zapcp1252/blob/master/lib/Encode/ZapCP1252.pm#L45).

**Comment by khwilliamson** [comment]
On 02/10/2015 11:30 AM, David E. Wheeler wrote:
> I assume you mean these
> <https://github.com/theory/encode-zapcp1252/blob/master/lib/Encode/ZapCP1252.pm#L45>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theory/pod-simple/pull/64#issuecomment-73754835>.
>

Yes.

The commit you referred to doesn't make sense to me.  The message says 
that it's trying to get rid of any UTF-8 stuff, but it also comments out 
stuff in that code reference that attempted to do that.

If you want to do translations in 5.6, given that comment, maybe instead 
of going to Unicode in that release we should go to the ascii versions,

https://github.com/theory/encode-zapcp1252/blob/master/lib/Encode/ZapCP1252.pm#L14

and test for that in encod04 in early Perls.  That seems safest to me.

Maybe it would be better to be using irc, to get rid of the response delays?

**Pull request merged**
